__authors__ = "Peter Burek, Johan van der Knijff, Ad de Roo"
__version__ = "0.3.4"
__date__ = "23/05/2019"
__copyright__ = "Copyright 2019, Lisflood Open Source"
__maintainers__ = "Domenico Nappo, Valerio Lorini, Lorenzo Mentaschi"
__status__ = "Development"
