name: lisvap
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.13
  - attr=2.5.1
  - aws-c-auth=0.8.0
  - aws-c-cal=0.8.0
  - aws-c-common=0.10.3
  - aws-c-compression=0.3.0
  - aws-c-event-stream=0.5.0
  - aws-c-http=0.9.1
  - aws-c-io=0.15.2
  - aws-c-mqtt=0.11.0
  - aws-c-s3=0.7.3
  - aws-c-sdkutils=0.2.1
  - aws-checksums=0.2.2
  - aws-crt-cpp=0.29.6
  - aws-sdk-cpp=1.11.449
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - blosc=1.21.6
  - bzip2=1.0.8
  - c-ares=1.34.3
  - ca-certificates=2025.4.26
  - cairo=1.18.0
  - capnproto=1.0.2
  - cdo=2.4.4
  - cfitsio=4.4.1
  - cyrus-sasl=2.1.27
  - dbus=1.13.6
  - eccodes=2.39.0
  - expat=2.6.4
  - fftw=3.3.10
  - findlibs=0.0.5
  - fmt=11.0.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freeglut=3.2.2
  - freetype=2.12.1
  - freexl=2.0.0
  - fribidi=1.0.10
  - gdal=3.9.2
  - geos=3.13.0
  - geotiff=1.7.3
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - giflib=5.2.2
  - glib=2.82.2
  - glib-tools=2.82.2
  - graphite2=1.3.13
  - gst-plugins-base=1.24.7
  - gstreamer=1.24.7
  - harfbuzz=9.0.0
  - hdf4=4.2.15
  - hdf5=1.14.3
  - icu=75.1
  - jasper=4.2.5
  - json-c=0.18
  - kealib=1.5.3
  - keyutils=1.6.1
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.3
  - libarchive=3.7.7
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libboost=1.86.0
  - libcap=2.69
  - libcblas=3.9.0
  - libclang-cpp19.1=19.1.4
  - libclang13=19.1.4
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=8.10.1
  - libdeflate=1.22
  - libdrm=2.4.123
  - libedit=3.1.20191231
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.4
  - libffi=3.4.2
  - libflac=1.4.3
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgcrypt=1.11.0
  - libgcrypt-devel=1.11.0
  - libgcrypt-lib=1.11.0
  - libgcrypt-tools=1.11.0
  - libgdal=3.9.2
  - libgdal-core=3.9.2
  - libgdal-fits=3.9.2
  - libgdal-grib=3.9.2
  - libgdal-hdf4=3.9.2
  - libgdal-hdf5=3.9.2
  - libgdal-jp2openjpeg=3.9.2
  - libgdal-kea=3.9.2
  - libgdal-netcdf=3.9.2
  - libgdal-pdf=3.9.2
  - libgdal-pg=3.9.2
  - libgdal-postgisraster=3.9.2
  - libgdal-tiledb=3.9.2
  - libgdal-xls=3.9.2
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libgl=1.7.0
  - libglib=2.82.2
  - libglu=9.0.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=14.2.0
  - libgoogle-cloud=2.31.0
  - libgoogle-cloud-storage=2.31.0
  - libgpg-error=1.51
  - libgrpc=1.67.1
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm19=19.1.4
  - libnetcdf=4.9.2
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libntlm=1.4
  - libogg=1.3.5
  - libopenblas=0.3.28
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.44
  - libpq=17.2
  - libprotobuf=5.28.2
  - libre2-11=2024.07.02
  - librttopo=1.1.0
  - libsndfile=1.2.2
  - libspatialite=5.1.0
  - libsqlite=3.47.0
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libsystemd0=256.7
  - libtiff=4.7.0
  - libudunits2=2.2.28
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp-base=1.4.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.7.0
  - libxml2=2.13.5
  - libxslt=1.1.39
  - libzip=1.11.2
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - lzo=2.10
  - magics=4.15.5
  - magics-python=1.5.8
  - minizip=4.0.7
  - mpg123=1.32.9
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - ncurses=6.5
  - nspr=4.36
  - nss=3.107
  - numpy=1.24.4
  - openjpeg=2.5.2
  - openldap=2.6.9
  - openssl=3.5.0
  - packaging=24.2
  - pango=1.54.0
  - pcraster=4.4.1
  - pcre2=10.44
  - pip=24.3.1
  - pixman=0.43.2
  - poppler=24.11.0
  - poppler-data=0.4.12
  - postgresql=17.2
  - proj=9.5.1
  - pthread-stubs=0.4
  - pulseaudio-client=17.0
  - python=3.8.20
  - python_abi=3.8
  - qt-main=5.15.15
  - re2=2024.07.02
  - readline=8.2
  - s2n=1.5.9
  - setuptools=75.3.0
  - simplejson=3.19.3
  - snappy=1.2.1
  - spdlog=1.14.1
  - sqlite=3.47.0
  - tiledb=2.26.2
  - tk=8.6.13
  - tzcode=2024b
  - tzdata=2024b
  - udunits2=2.2.28
  - uriparser=0.9.8
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xerces-c=3.2.5
  - xkeyboard-config=2.43
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.10
  - xorg-libxau=1.0.11
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrender=0.9.11
  - xorg-libxxf86vm=1.1.5
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xorgproto=2024.1
  - xz=5.2.6
  - zlib=1.3.1
  - zstd=1.5.6
  - pip:
      - cachetools==5.5.0
      - certifi==2024.8.30
      - cftime==1.6.4.post1
      - chardet==5.2.0
      - colorama==0.4.6
      - coverage==7.6.1
      - cython==3.0.11
      - distlib==0.3.9
      - docopt==0.6.2
      - exceptiongroup==1.2.2
      - filelock==3.16.1
      - future==1.0.0
      - iniconfig==2.0.0
      - netcdf4==1.7.2
      - nine==1.1.0
      - pathlib2==2.3.7.post1
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - pyproj==3.5.0
      - pyproject-api==1.8.0
      - pytest==8.3.4
      - pytest-cov==5.0.0
      - python-dateutil==2.9.0.post0
      - six==1.16.0
      - tomli==2.2.1
      - tox==4.23.2
      - typing-extensions==4.12.2
      - virtualenv==20.28.0
